// var octoPix = [   "https://octodex.github.com/images/adventure-cat.png",
//                   "https://octodex.github.com/images/linktocat.jpg",
//                   "https://octodex.github.com/images/megacat.jpg",
//                   "https://octodex.github.com/images/plumber.jpg",
//                   "https://octodex.github.com/images/riddlocat.png",
//                   "https://octodex.github.com/images/scarletteocat.jpg",
//                   "https://octodex.github.com/images/poptocat.png",
//                   "https://octodex.github.com/images/xtocat.jpg",
//                   "https://octodex.github.com/images/cherryontop-o-cat.png",
//                   "https://octodex.github.com/images/okal-eltocat.jpg"];